bbc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('bbc_dashboard.urls')),
    url(r'', include('bbc_db.urls'))
]

bbc_dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = "bbc_dashboard"
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^login$',views.login,name='login'),
    url(r'^register$',views.register,name='register'),
    url(r'^student$',views.student, name='student'),
    url(r'^student/data$',views.studentdata, name='student.data'),
    url(r'^class$',views.showclass,name='class'),
    url(r'^class/data$',views.classdata,name='class.data'),
    url(r'^class/data/date=(?P<date>.*)$',views.classdatabydate,name='class.data.bydate'),
    url(r'^class/data/class=(?P<class_id>.*)&date=(?P<date>.*)$',views.classdatadetail,name='class.data.detail'),
    url(r'^parent$',views.parent,name="parent"),
    url(r'^parent/data$', views.parentdata, name="parent.data"),
    url(r'^instructor$',views.instructor,name='instructor'),
    url(r'^instructor/data$',views.instructordata,name='instructor.data'),
    url(r'^fees$',views.fees,name='fees'),
    url(r'^fees/data$',views.feesdata,name='fees.data'),
    url(r'^rank$',views.rank,name='rank'),
    url(r'^rank/data$',views.rankdata,name='rank.data'),
    url(r'^attendance$',views.attendance,name='attendance'),
    url(r'^attendancedata$',views.attendancedata,name='attendance.data'),
    url(r'^stat$',views.stat,name="stat"),
    url(r'^studentStatUrl$',views.studentStat,name='stat.student'),
    url(r'^rankStatUrl$',views.rankStat,name='stat.rank'),
    url(r'^attendanceStatUrl$',views.attendanceStat,name="stat.att")
]

bbc_db/urls.py
from django.conf.urls import url

from . import views

app_name = "bbc_db"
urlpatterns = [
    url(r'^addStudent$',views.addStudent, name='addStudent'),
    url(r'^modifyStudent$',views.modifyStudent, name='modifyStudent'),
    url(r'^deleteStudent$',views.deleteStudent, name='deleteStudent'),
    url(r'^addClass$',views.addClass, name='addClass'),
    url(r'^modifyClass$',views.modifyClass, name='modifyClass'),
    url(r'^deleteClass$',views.deleteClass,name='deleteClass'),
    url(r'^addParent$',views.addParent, name='addParent'),
    url(r'^modifyParent$',views.modifyParent,name='modifyParent'),
    url(r'^deleteParent$',views.deleteParent,name='deleteParent'),
    url(r'^addInstructor$',views.addInstructor,name='addInstructor'),
    url(r'^modifyInstructor$',views.modifyInstructor,name='modifyInstructor'),
    url(r'^deleteInstructor$',views.deleteInstructor,name='deleteInstructor'),
    url(r'^addFees$',views.addFees,name='addFees'),
    url(r'^deleteFees$',views.deleteFees,name='deleteFees'),
    url(r'^addRank$',views.addRank,name='addRank'),
    url(r'^deleteRank$',views.deleteRank,name='deleteRank'),
    url(r'^addAttendance$',views.addAttendance,name='addAttendance'),
    url(r'^deteleAttendance$',views.deleteAttendance,name='deleteAttendance'),
    url(r'^findParentById$',views.findParentById,name='findParentById'),
    url(r'^findStudentByParId/id=(?P<par_id>.*)?.*$',views.findStudentByParId,name='findStudentByParId'),
]

bbc_dashboard/models.py
from django.db import models

# Create your models here.

bbc_dashboard/views.py
from django.shortcuts import render,HttpResponse
from django.contrib.auth import authenticate,login as ll
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import MultipleObjectsReturned
from bbc_db.models import *
from django.db import connection
import json, logging

# Create your views here.

def index(request):
    return render(request,'index.html')


def login(request):
    if request.method == 'POST':
        # get parameters from request.POST
        username = request.POST['Username'].strip()
        password = request.POST['Password'].strip()
        user = authenticate(username=username, password=password)
        # authentication success
        if user is not None:
            # update information in user table
            ll(request,user)
            # redirect
            return render(request,'bbc_dashboard/main.html',context={"username":username})
        # authentication fail
        else:
            return render(request,'index.html',context={
                "flag":"WrongPassword"
            })
    else:
        return render(request,'index.html',context={
                "flag":"WrongPassword"
            })
    

def register(request):
    if request.method == 'POST':
        # get parameters from request.POST
        username = request.POST['Username'].strip()
        password = request.POST['Password'].strip()
        email = request.POST['Email'].strip()
        try:
            # check if the username has already been used
            user = User.objects.get(username=username)
        # no record has the same username
        except ObjectDoesNotExist:
            # create the account and redirect
            user = User.objects.create_user(username=username,email=email, password=password)
            ll(request,user)
            user.save()
            # redirect
            return render(request,'bbc_dashboard/main.html',context={"username":username})
        # multiple records with same username are found
        except MultipleObjectsReturned:
            return render(request,'index.html',context={
                "flag":"Existed"
            })

        return render(request,'index.html',context={
                "flag":"Existed"
            })

def student(request):
    return render(request,'bbc_dashboard/student.html')

def studentdata(request):
    objects = Student.objects.all()
    obj = [dict({'id':i+1},**(objects[i]).as_dict()) for i in range(len(objects))]
    for i in range(len(obj)):
        par_id = obj[i]['par_id']
        try:
            name = Parent.objects.get(par_id=par_id).par_name
        except ObjectDoesNotExist:
            name = None
        obj[i]['std_parent'] = name
    obj = json.dumps(obj)
    return HttpResponse(obj,content_type="applicetion/json")

def showclass(request):
    inst_objs = [x.as_dict() for x in Instructor.objects.all()]
    return render(request,'bbc_dashboard/class.html',context={
        'insts':inst_objs
        })

def classdata(request):
    objects = Class.objects.all()
    obj = [dict({"id":i+1},**(objects[i]).as_dict()) for i in range(len(objects))]
    obj = json.dumps(obj)
    return HttpResponse(obj,content_type="application/json")

def classdatabydate(request,date):
    logging.debug(date)
    objects = Class.objects.all().filter(class_day=date)
    obj = [dict({"id":i+1},**(objects[i]).as_dict()) for i in range(len(objects))]
    obj = json.dumps(obj)
    return HttpResponse(obj,content_type="application/json")


def parent(request):
    return render(request, 'bbc_dashboard/parent.html')

def parentdata(request):
    objects = Parent.objects.all()
    obj = [dict({"id":i+1},**(objects[i]).as_dict()) for i in range(len(objects))]
    obj = json.dumps(obj)
    return HttpResponse(obj,content_type="application/json")

def instructor(request):
    return render(request, 'bbc_dashboard/instructor.html')

def instructordata(request):
    objects = Instructor.objects.all()
    obj = [dict({"id":i+1},**(objects[i]).as_dict()) for i in range(len(objects))]
    obj = json.dumps(obj)
    return HttpResponse(obj,content_type='application/json')

def fees(request):
    return render(request,'bbc_dashboard/fees.html')

def feesdata(request):
    objects = Fees.objects.all()
    obj = [dict({"id":i+1},**(objects[i]).as_dict()) for i in range(len(objects))]
    for x in obj:
        std_id = x['std_id']
        std = Student.objects.get(std_id=std_id)
        x['std'] = std.std_name
    obj = json.dumps(obj)
    return HttpResponse(obj,content_type='application/json')


def rank(request):
    return render(request,'bbc_dashboard/rank.html')

def rankdata(request):
    objects = Rank.objects.all()
    obj = [dict({"id":i+1},**(objects[i]).as_dict()) for i in range(len(objects))]
    for x in obj:
        std_id = x['std_id']
        std = Student.objects.get(std_id=std_id)
        x['std'] = std.std_name
    obj = json.dumps(obj)
    return HttpResponse(obj,content_type="application/json")

def attendance(request):
    return render(request,'bbc_dashboard/attendance.html')

def attendancedata(request):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute('SELECT DISTINCT ATT_CLASS,ATT_DATE FROM ATTENDANCE')
        r_list= cursor.fetchall()
    
    objects = [0]*len(r_list)
    for index,value in enumerate(r_list):
        class_id = value[0]
        date = value[1]
        class_obj = Class.objects.get(class_id=class_id)
        objects[index] = class_obj.as_dict()
        objects[index]['id'] = index+1
        objects[index]['date'] = date
    return HttpResponse(json.dumps(objects),content_type="application/json")

def classdatadetail(request,class_id,date):
    att_list = Attendance.objects.all().filter(class_field_id=class_id,att_date=date)
    objects = [0]*len(att_list)
    for index, value in enumerate(att_list):
        std_id = value.std_id
        std_object = Student.objects.get(std_id=std_id)
        objects[index] = dict({"id":index+1},**(std_object).as_dict())
    
    return HttpResponse(json.dumps(objects),content_type="application/json") 

def stat(request):
    return render(request,'bbc_dashboard/stat.html')

def studentStat(request):
    dobList = Student.objects.values("std_dob")
    data = []
    res = [0,0]
    for x in dobList:
        if dayToToday(x['std_dob']) >= 18*365:
            res[0] += 1
        else:
            res[1] += 1
    data.append(res)

    dojoinList = Student.objects.values("std_dojoin")
    dd = {}
    res = []
    for x in dojoinList:
        t = x['std_dojoin']
        t = t[:t.rfind('-')]
        dd[t] = dd.get(t,0) + 1
    dd = dd.items()
    res = [{"t":x[0],"y":x[1]} for x in dd]
    data.append(res)
    return HttpResponse(json.dumps(data),content_type="application/json")


def rankStat(request):
    rankList = Rank.objects.values("rank_color")
    dd = {}
    data = []
    for x in rankList:
        t = x['rank_color']
        dd[t] = dd.get(t,0) + 1
    res = [x[1] for x in dd.items()]
    data.append({"data":res,"labels":list(dd.keys())})
    return HttpResponse(json.dumps(data),content_type="application/json")

 
def attendanceStat(request):
    data = []
    with connection.cursor() as cursor:
        cursor.execute("SELECT CLASS_NAME, avg(times) FROM (select COUNT(ATT_STD) as times,CLASS_NAME from bbc.attendance a,bbc.class b where a.ATT_CLASS = b.CLASS_ID group by ATT_CLASS,ATT_DATE) b group by b.CLASS_name;")
        row = cursor.fetchall()
        res = {}
        res['data'] = [{"x":x[0],"y":float(x[1])} for x in row]
        res['labels'] = [x[0] for x in row]
        data.append(res)

    with connection.cursor() as cursor:
        cursor.execute("select count(class_id), class_level, class_time from bbc.attendance a, bbc.class b where a.ATT_CLASS = b.CLASS_ID group by CLASS_LEVEL,CLASS_TIME;")
        row = cursor.fetchall()
        res = {}
        res['data'] = [{"x":"2017-01-01 "+x[2],"y":x[1],"r":x[0]} for x in row]
        res['labels'] = [x[1] for x in row]
        data.append(res)

    return HttpResponse(json.dumps(data),content_type="application/json")


def dayToToday(time1):
    import datetime
    today = datetime.datetime.combine(datetime.date.today(),datetime.time())
    time1 = datetime.datetime.strptime(time1,"%Y-%m-%d")
    return (today - time1).days

templates/bbc_dashboard/class.html
	<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
	<html>
	<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<title>Search</title>

	<link rel="stylesheet" href="{% static 'lib/bootstrap.min.css' %}" >
	<script src="{% static 'lib/jquery-2.1.4.min.js' %}"></script>
	<script src="{% static 'lib/bootstrap.min.js' %}"></script>

	<link rel="stylesheet" href="{% static 'bbc_dashboard/css/index.css' %}" >
	<link href="{% static 'lib/bootstrap-table.css' %}" rel="stylesheet">
	<link href="{% static 'lib/clockpicker.css' %}" rel="stylesheet">
	<script src="{% static 'lib/js.cookie.js' %}"></script>
	<script src="{% static 'bbc_dashboard/js/util.js' %}"></script>
	<script src="{% static 'bbc_dashboard/js/class.js' %}"></script>
	<script src="{% static 'lib/bootstrap-table.js' %}"></script>
	<script src="{% static 'lib/clockpicker.js' %}"></script>
	</head>
	<body>
	<div class="container-fluid">
		<div id="toolbar" class="btn-group">
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal" id='btn_add'>ADD</button>
		</div>
		<table id="classTable" 
				data-url={% url 'bbc_dashboard:class.data' %}
				data-show-toggle="true"
				data-search="true"           
				data-show-filter="true"
				data-striped="true"
				data-sort="name"
				data-toolbar="#toolbar"
				data-sort-order="desc">
			<thead>
			<tr>
				<th data-field="id" data-width="20" data-align="left" data-sortable="true">No</th>
				<th data-visible=false data-field="class_id" data-width="30" data-align="left">Id</th>
				<th data-visible=false data-field="inst_id" data-width="30" data-align="left">Inst_Id</th>
				<th data-field="class_name" data-width="30" data-align="left" data-sortable="true">Name</th>
				<th data-field="class_level" data-width="25" data-align="left" data-sortable="true">Level</th>
				<th data-field="class_day" data-width="25" data-align="left" data-sortable="true">Day</th>
				<th data-field="class_time"data-width="80" data-align="left" data-sortable="true">Time</th>
				<th data-field="inst"data-width="80" data-align="left" data-sortable="true">Instructor</th>
				<th data-field="modify" data-width="20" data-formatter="modifyFormatter" data-events="modifyEvents">Modify</th>
				<th data-field="remove" data-width="20" data-formatter="removeFormatter" data-events="removeEvents">Remove</th>
			</tr>
			</thead>
		</table>
	</div>

<div class="modal fade" id="modifyModal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-hidden="true">x
				</button>
				<h4 class="modal-title" id="myModalLabel">
					Modify a class
				</h4>
			</div>
			<div class="modal-body">
				<form class="bs-example bs-example-form" role="form" id="modifyClassForm" method="POST" action="{% url 'bbc_db:modifyClass' %}">
					{% csrf_token %} 
					<input type="hidden" id='modify_id' name='id'>
					<div class="input-group">
						<span class="input-group-addon">Name</span>
						<input type="text" class="form-control comp_sponsor" style="width: 200px" id="modify_name" name="name"  placeholder="name">
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">Day of Week</span>
						<select type="text" class="form-control" name="day" id="modify_day" style="width: 200px">
							<option value="Monday">Monday</option>
							<option value="Tuesday">Tuesday</option>
							<option value="Wednesday">Wednesday</option>
							<option value="Thursday">Thursday</option>
							<option value="Friday">Friday</option>
							<option value="Saturday">Saturday</option>
							<option value="Sunday">Sunday</option>
						</select>
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">Level</span>
						<select type="text" class="form-control" name="level" id="modify_level" style="width: 200px">
							<option value="Beginner">Beginner</option>
							<option value="Intermediate">Intermediate</option>
							<option value="Advanced">Advanced</option>
						</select>
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">Instructor</span>
						<select type="text" class="form-control" name="inst" id="modify_inst" style="width: 200px">
							{% for inst in insts %}
								<option value="{{ inst.inst_id }}">{{ inst.inst_lname }}</option>
							{% endfor %}
						</select>
					</div>
					<br>
					<div class="form-group">
						<div class="input-group date date col-md-3 " id="modify_time" data-date="" data-date-format="hh:ii" data-link-field="motify_time_input" data-link-format="hh:ii">
							<label for="modify_time_input" class="input-group-addon control-label">Time</label>
							<input class="form-control" id="modify_time_input" name="time" size="8" type="text" value="" readonly>
							<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" 
				data-dismiss="modal">close
				</button>
				<button type="button" class="btn btn-primary" id='sendConfirm2' data-dismiss="modal" data-toggle="modal" data-target="#confirmModal2">
				add
				</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-hidden="true">x
				</button>
				<h4 class="modal-title" id="myModalLabel">
					Create a class
				</h4>
			</div>
			<div class="modal-body">
				<form class="bs-example bs-example-form" role="form" id="addClassForm" method="POST" action="{% url 'bbc_db:addClass' %}">
					{% csrf_token %} 
					<div class="input-group">
						<span class="input-group-addon">Name</span>
						<input type="text" class="form-control comp_sponsor" style="width: 200px" id="add_name" name="name"  placeholder="name">
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">Day of Week</span>
						<select type="text" class="form-control" name="day" id="add_day" style="width: 200px">
							<option value="Monday">Monday</option>
							<option value="Tuesday">Tuesday</option>
							<option value="Wednesday">Wednesday</option>
							<option value="Thursday">Thursday</option>
							<option value="Friday">Friday</option>
							<option value="Saturday">Saturday</option>
							<option value="Sunday">Sunday</option>
						</select>
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">Level</span>
						<select type="text" class="form-control" name="level" id="add_level" style="width: 200px">
							<option value="Beginner">Beginner</option>
							<option value="Intermediate">Intermediate</option>
							<option value="Advanced">Advanced</option>
						</select>
					</div>
					<br>
					<div class="input-group">
						<span class="input-group-addon">Instructor</span>
						<select type="text" class="form-control" name="inst" id="add_inst" style="width: 200px">
							{% for inst in insts %}
								<option value="{{ inst.inst_id }}">{{ inst.inst_lname }}</option>
							{% endfor %}
						</select>
					</div>
					<br>
					<div class="form-group">
						<div class="input-group date date col-md-3 " id="add_time" data-date="" data-date-format="hh:ii" data-link-field="add_time_input" data-link-format="hh:ii">
							<label for="add_time_input" class="input-group-addon control-label">Time</label>
							<input class="form-control" id="add_time_input" name="time" size="8" type="text" value="" readonly>
							<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" 
				data-dismiss="modal">close
				</button>
				<button type="button" class="btn btn-primary" id='sendConfirm' data-dismiss="modal" data-toggle="modal" data-target="#confirmModal">
				add
				</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" 
				aria-hidden="true">x
			</button>
			<h4 class="modal-title" id="myModalLabel">
				Confirmation
			</h4>
			</div>
			<div class="modal-body">
			Please make sure everything is correct!
			</div>
			<div class="modal-footer">
			<button type="button" class="btn btn-default" 
				data-dismiss="modal">Close
			</button>
			<button type="button" class="btn btn-primary" id='addClassConfirm' data-dismiss="modal">
				Confirm
			</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="confirmModal2" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" 
				aria-hidden="true">x
			</button>
			<h4 class="modal-title" id="myModalLabel">
				Confirmation
			</h4>
			</div>
			<div class="modal-body">
			Please make sure everything is correct!
			</div>
			<div class="modal-footer">
			<button type="button" class="btn btn-default" 
				data-dismiss="modal">Close
			</button>
			<button type="button" class="btn btn-primary" id='modifyClassConfirm' data-dismiss="modal">
				Confirm
			</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

</body>
</html>

templates/bbc_dashboard/fees.html
	<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
	<html>
	<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<title>Search</title>

	<link rel="stylesheet" href="{% static 'lib/bootstrap.min.css' %}" >
	<script src="{% static 'lib/jquery-2.1.4.min.js' %}"></script>
	<script src="{% static 'lib/bootstrap.min.js' %}"></script>

	<link rel="stylesheet" href="{% static 'bbc_dashboard/css/index.css' %}" >
	<link href="{% static 'lib/bootstrap-table.css' %}" rel="stylesheet">
	<link href="{% static 'lib/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
	
	<script src="{% static 'lib/js.cookie.js' %}"></script>
	<script src="{% static 'bbc_dashboard/js/util.js' %}"></script>

	<script src="{% static 'bbc_dashboard/js/fees.js' %}"></script>
	<script src="{% static 'lib/bootstrap-table.js' %}"></script>
	<script src="{% static 'lib/bootstrap-datetimepicker.js' %}"></script>
	
	</head>
	<body>
	<div class="container-fluid">
		<div id="toolbar" class="btn-group">
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal" id='btn_add'>ADD</button>
		</div>
		<table id="feesTable" 
				data-url={% url 'bbc_dashboard:fees.data' %}
				data-show-toggle="true"
				data-search="true"           
				data-show-filter="true"
				data-striped="true"
				data-sort="name"
				data-toolbar="#toolbar"
				data-sort-order="desc">
			<thead>
			<tr>
				<th data-field="id" data-width="20" data-align="left" data-sortable="true">No</th>
				<th data-visible=false data-field="fees_id" data-width="30" data-align="left">Id</th>
				<th data-field="std" data-width="30" data-align="left">Student</th>
				<th data-field="fees_type" data-width="25" data-align="left" data-sortable="true">Type</th>
				<th data-field="fees_amount" data-width="25" data-align="left" data-sortable="true">Amount</th>
				<th data-field="fees_date"data-width="80" data-align="left" data-sortable="true">Date</th>
				<th data-field="remove" data-width="20" data-formatter="removeFormatter" data-events="removeEvents">Remove</th>
			</tr>
			</thead>
		</table>
	</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-hidden="true">x
				</button>
				<h4 class="modal-title" id="myModalLabel">
					Generate a new fees record
				</h4>
			</div>
			<div class="modal-body">
				<form class="form-group" role="form" id="addFeesForm" method="POST" action="{% url 'bbc_db:addFees' %}">
					{% csrf_token %} 
					<div class="input-group">
						<span class="input-group-addon">Type</span>
						<select class="form-control" style="width: 200px" id="add_type" name="type"  >
							<option value="Tuition">Tuition Fee</option>
							<option value="Costume">Costume Fee</option>
							<option value="Insurance">Insurance Fee</option>
							<option value="Utility">Utility Fee</option>
						</select>
					</div>
					<br>
					<div class="input-group" style="width:250px">
						<span class="input-group-addon">Amount</span>
						<input type="number" class="form-control" id="add_amount" name="amount"  placeholder="amount">
						<span class="input-group-addon">CAD</span>
					</div>
					<br>
					<input type="hidden" id="addDate" name="date">
					<input type="hidden" id="addStdId" name="std_id">
					<div id="addStudentDiv">
						<table id="addStudentTable" 
							data-url={% url 'bbc_dashboard:student.data' %}
							data-search="true"           
							data-show-filter="true"
							data-striped="true"
							data-sort="name"
							data-sort-order="desc">
						<thead>
						<tr>
							<th data-field="state" data-radio="true"></th>
							<th data-field="id" data-width="20" data-align="left" data-sortable="true">No</th>
							<th data-visible=false data-field="std_id" data-width="30" data-align="left">std_id</th>
							<th data-field="std_name" data-width="30" data-align="left" data-sortable="true">Name</th>
							<th data-field="std_email"data-width="80" data-align="left" data-sortable="true">Email</th>
							<th data-field="std_mobilenumber"data-width="80" data-align="left" data-sortable="true">Mobile</th>
						</tr>
						</thead>
					</table>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" 
				data-dismiss="modal">close
				</button>
				<button type="button" class="btn btn-primary" id='sendConfirm' data-dismiss="modal" data-toggle="modal" data-target="#confirmModal">
				add
				</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" 
				aria-hidden="true">x
			</button>
			<h4 class="modal-title" id="myModalLabel">
				Confirmation
			</h4>
			</div>
			<div class="modal-body">
			Please make sure everything is correct!
			</div>
			<div class="modal-footer">
			<button type="button" class="btn btn-default" 
				data-dismiss="modal">Close
			</button>
			<button type="button" class="btn btn-primary" id='addFeesConfirm' data-dismiss="modal">
				Confirm
			</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->


</body>
</html>